//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP.Web.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("APP.Web.Common.Properties.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can only contain alphanumeric and -.
        /// </summary>
        internal static string AccountNumber {
            get {
                return ResourceManager.GetString("AccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can only contain alphanumeric characters.
        /// </summary>
        internal static string AffiliateCode {
            get {
                return ResourceManager.GetString("AffiliateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affiliate code not found :.
        /// </summary>
        internal static string AffiliateNotFound {
            get {
                return ResourceManager.GetString("AffiliateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, following affiliate not found or they don&apos;t belong to chosen currency :.
        /// </summary>
        internal static string AffiliateNotFoundByCurrency {
            get {
                return ResourceManager.GetString("AffiliateNotFoundByCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Applicant  must greater than.
        /// </summary>
        internal static string ApplicantQty {
            get {
                return ResourceManager.GetString("ApplicantQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A promotion transaction cannot be approved twice, please refresh this page..
        /// </summary>
        internal static string ApprovalTwice {
            get {
                return ResourceManager.GetString("ApprovalTwice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Award Description should less than 4000, .
        /// </summary>
        internal static string AwardDescriptionMaxLength {
            get {
                return ResourceManager.GetString("AwardDescriptionMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T&amp;C in English Language should less than 10000,.
        /// </summary>
        internal static string ConditionEngMaxLength {
            get {
                return ResourceManager.GetString("ConditionEngMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T&amp;C in Indoneisa Language should less than 10000,.
        /// </summary>
        internal static string ConditionIdnMaxLength {
            get {
                return ResourceManager.GetString("ConditionIdnMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T&amp;C in Khmer Language should less than 10000,.
        /// </summary>
        internal static string ConditionKhmMaxLength {
            get {
                return ResourceManager.GetString("ConditionKhmMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T&amp;C in Thai Language should less than 10000,.
        /// </summary>
        internal static string ConditionThaMaxLength {
            get {
                return ResourceManager.GetString("ConditionThaMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T&amp;C in Vietnamese Language should less than 10000,.
        /// </summary>
        internal static string ConditionVieMaxLength {
            get {
                return ResourceManager.GetString("ConditionVieMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please be sure to fill in the correct order to avoid delays in the time of payment.
        /// </summary>
        internal static string ConfirmCorrectOrder {
            get {
                return ResourceManager.GetString("ConfirmCorrectOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Email should be same as Email.
        /// </summary>
        internal static string ConfirmEmail {
            get {
                return ResourceManager.GetString("ConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password should be same as Password.
        /// </summary>
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Number Existed.
        /// </summary>
        internal static string ContactNoExist {
            get {
                return ResourceManager.GetString("ContactNoExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can only contain number.
        /// </summary>
        internal static string ContactNumber {
            get {
                return ResourceManager.GetString("ContactNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description in English Language should less than 10000,.
        /// </summary>
        internal static string DescriptionEngMaxLength {
            get {
                return ResourceManager.GetString("DescriptionEngMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description in Indoneisa Language should less than 10000,.
        /// </summary>
        internal static string DescriptionIdnMaxLength {
            get {
                return ResourceManager.GetString("DescriptionIdnMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description in Khmer Language should less than 10000,.
        /// </summary>
        internal static string DescriptionKhmMaxLength {
            get {
                return ResourceManager.GetString("DescriptionKhmMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description in Thai Language should less than 10000,.
        /// </summary>
        internal static string DescriptionThaMaxLength {
            get {
                return ResourceManager.GetString("DescriptionThaMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description in Vietnamese Language should less than 10000,.
        /// </summary>
        internal static string DescriptionVieMaxLength {
            get {
                return ResourceManager.GetString("DescriptionVieMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective Date should less than 4000, .
        /// </summary>
        internal static string EffectiveDateMaxLength {
            get {
                return ResourceManager.GetString("EffectiveDateMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Format is wrong.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Exist.
        /// </summary>
        internal static string EmailExist {
            get {
                return ResourceManager.GetString("EmailExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error:  .
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be number.
        /// </summary>
        internal static string FieldDigits {
            get {
                return ResourceManager.GetString("FieldDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can only contain numbers up to four decimal places.
        /// </summary>
        internal static string FieldFourDecimal {
            get {
                return ResourceManager.GetString("FieldFourDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required.
        /// </summary>
        internal static string FieldRequired {
            get {
                return ResourceManager.GetString("FieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can only contain numbers up to two decimal places.
        /// </summary>
        internal static string FieldTwoDecimal {
            get {
                return ResourceManager.GetString("FieldTwoDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can only contain numbers up to Zero decimal places.
        /// </summary>
        internal static string FieldZeroDecimal {
            get {
                return ResourceManager.GetString("FieldZeroDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length must be between 3 to 13.
        /// </summary>
        internal static string ForbiddenKeyword_Length {
            get {
                return ResourceManager.GetString("ForbiddenKeyword_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be 4 digits.
        /// </summary>
        internal static string FourDigits {
            get {
                return ResourceManager.GetString("FourDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency date to must greater than frequency date from..
        /// </summary>
        internal static string FrequencyDate {
            get {
                return ResourceManager.GetString("FrequencyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency time to must greater than frequency time from..
        /// </summary>
        internal static string FrequencyTime {
            get {
                return ResourceManager.GetString("FrequencyTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format Time From is wrong.
        /// </summary>
        internal static string FrequencyTimeFrom {
            get {
                return ResourceManager.GetString("FrequencyTimeFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format Time To is wrong.
        /// </summary>
        internal static string FrequencyTimeTo {
            get {
                return ResourceManager.GetString("FrequencyTimeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How To Apply  should less than 4000, .
        /// </summary>
        internal static string HowToApplyMaxLength {
            get {
                return ResourceManager.GetString("HowToApplyMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect amount : .
        /// </summary>
        internal static string IncorrectAmount {
            get {
                return ResourceManager.GetString("IncorrectAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be a number between -1,000,000,000 and 1,000,000,000, except 0.
        /// </summary>
        internal static string Int_NegativeOnebillion_OneBillion_NoZero {
            get {
                return ResourceManager.GetString("Int_NegativeOnebillion_OneBillion_NoZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be between 1 and 1,000,000,000.
        /// </summary>
        internal static string Int_One_OneBillion {
            get {
                return ResourceManager.GetString("Int_One_OneBillion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be between 0 and 1,000,000,000.
        /// </summary>
        internal static string Int_Zero_OneBillion {
            get {
                return ResourceManager.GetString("Int_Zero_OneBillion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can only contain number.
        /// </summary>
        internal static string Invalid_BetNo {
            get {
                return ResourceManager.GetString("Invalid_BetNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can only contain number.
        /// </summary>
        internal static string Invalid_DrawNo {
            get {
                return ResourceManager.GetString("Invalid_DrawNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Time, format should be like hh:mm:ss.
        /// </summary>
        internal static string Invalid_Time {
            get {
                return ResourceManager.GetString("Invalid_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Time, format should be like hh:mm.
        /// </summary>
        internal static string Invalid_Time_Without_Second {
            get {
                return ResourceManager.GetString("Invalid_Time_Without_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyword already exists.
        /// </summary>
        internal static string KeywordExists {
            get {
                return ResourceManager.GetString("KeywordExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length should less than 15.
        /// </summary>
        internal static string Length_Fifteen {
            get {
                return ResourceManager.GetString("Length_Fifteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length should less than 50.
        /// </summary>
        internal static string Length_Fifty {
            get {
                return ResourceManager.GetString("Length_Fifty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length should between 5 to 20.
        /// </summary>
        internal static string Length_Five_Twenty {
            get {
                return ResourceManager.GetString("Length_Five_Twenty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length should less than 4000.
        /// </summary>
        internal static string Length_FourThousand {
            get {
                return ResourceManager.GetString("Length_FourThousand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length should less than 100.
        /// </summary>
        internal static string Length_OneHundred {
            get {
                return ResourceManager.GetString("Length_OneHundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length should less than 150.
        /// </summary>
        internal static string Length_OneHundredFifty {
            get {
                return ResourceManager.GetString("Length_OneHundredFifty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length should between 6 to 11.
        /// </summary>
        internal static string Length_Six_Eleven {
            get {
                return ResourceManager.GetString("Length_Six_Eleven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length should between 6 to 20.
        /// </summary>
        internal static string Length_Six_Twenty {
            get {
                return ResourceManager.GetString("Length_Six_Twenty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length should less than 30.
        /// </summary>
        internal static string Length_Thirty {
            get {
                return ResourceManager.GetString("Length_Thirty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length should less than 300.
        /// </summary>
        internal static string Length_ThreeHundred {
            get {
                return ResourceManager.GetString("Length_ThreeHundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length should less than 20.
        /// </summary>
        internal static string Length_Twenty {
            get {
                return ResourceManager.GetString("Length_Twenty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length should between 2 to 20.
        /// </summary>
        internal static string Length_Two_Twenty {
            get {
                return ResourceManager.GetString("Length_Two_Twenty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length should less than 200.
        /// </summary>
        internal static string Length_TwoHundred {
            get {
                return ResourceManager.GetString("Length_TwoHundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can only contain alphanumeric characters.
        /// </summary>
        internal static string LoginName {
            get {
                return ResourceManager.GetString("LoginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoginName Exist.
        /// </summary>
        internal static string LoginName_Exist {
            get {
                return ResourceManager.GetString("LoginName_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length should between 6 to 15.
        /// </summary>
        internal static string LoginName_Length {
            get {
                return ResourceManager.GetString("LoginName_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member code not found : .
        /// </summary>
        internal static string MemberNotFound {
            get {
                return ResourceManager.GetString("MemberNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, following members not found or they don&apos;t belong to chosen currency :.
        /// </summary>
        internal static string MemberNotFoundByCurrency {
            get {
                return ResourceManager.GetString("MemberNotFoundByCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be between -1,000,000,000 and 1,000,000,000.
        /// </summary>
        internal static string OneBillion_WithSign {
            get {
                return ResourceManager.GetString("OneBillion_WithSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must not contain your login name.
        /// </summary>
        internal static string PasswordContent {
            get {
                return ResourceManager.GetString("PasswordContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 6 characters long and contain at least one number and one character..
        /// </summary>
        internal static string PasswordLength {
            get {
                return ResourceManager.GetString("PasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must contain at least one number and one alphabet.
        /// </summary>
        internal static string PasswordPolicy {
            get {
                return ResourceManager.GetString("PasswordPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password must not be same as your current password.
        /// </summary>
        internal static string PasswordSame {
            get {
                return ResourceManager.GetString("PasswordSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input captcha.
        /// </summary>
        internal static string Please_Input_Captcha {
            get {
                return ResourceManager.GetString("Please_Input_Captcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input login name.
        /// </summary>
        internal static string Please_Input_Loginname {
            get {
                return ResourceManager.GetString("Please_Input_Loginname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input password.
        /// </summary>
        internal static string Please_Input_Password {
            get {
                return ResourceManager.GetString("Please_Input_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can only contain number and alphanumeric.
        /// </summary>
        internal static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotion Code Already Exists : .
        /// </summary>
        internal static string PromotionCodeExist {
            get {
                return ResourceManager.GetString("PromotionCodeExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error : Please fill out these fields : .
        /// </summary>
        internal static string PromotionError {
            get {
                return ResourceManager.GetString("PromotionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error :Promotion Name Already Exists, please update it and try again..
        /// </summary>
        internal static string PromotionNameExists {
            get {
                return ResourceManager.GetString("PromotionNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotion Name  should less than 12, .
        /// </summary>
        internal static string PromotionNameMaxLength {
            get {
                return ResourceManager.GetString("PromotionNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning : .
        /// </summary>
        internal static string PromotionWarning {
            get {
                return ResourceManager.GetString("PromotionWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length should between 6 to 13.
        /// </summary>
        internal static string QuickLoginName_Length {
            get {
                return ResourceManager.GetString("QuickLoginName_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length should between 6 to 14.
        /// </summary>
        internal static string RicheeLoginName_Length {
            get {
                return ResourceManager.GetString("RicheeLoginName_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency day to must greater than frequency day from..
        /// </summary>
        internal static string RoutineDay {
            get {
                return ResourceManager.GetString("RoutineDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency month to must greater than frequency month from ..
        /// </summary>
        internal static string RoutineMonth {
            get {
                return ResourceManager.GetString("RoutineMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule Description  should less than 4000, .
        /// </summary>
        internal static string RuleDescriptionMaxLength {
            get {
                return ResourceManager.GetString("RuleDescriptionMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url Format is wrong.
        /// </summary>
        internal static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
    }
}
