//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP.Web.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("APP.Web.Common.Properties.ErrorMessage", typeof(ErrorMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Account.
        /// </summary>
        internal static string ACCOUNT_NUMBER_NOT_VALID {
            get {
                return ResourceManager.GetString("ACCOUNT_NUMBER_NOT_VALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account tag type already exists..
        /// </summary>
        internal static string ACCOUNT_TAG_TYPE_DUPLICATE {
            get {
                return ResourceManager.GetString("ACCOUNT_TAG_TYPE_DUPLICATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affiliate already exist in system.
        /// </summary>
        internal static string AFFILIATE_RECORD_DUPLICATE {
            get {
                return ResourceManager.GetString("AFFILIATE_RECORD_DUPLICATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affiliate Code Not Allow Empty.
        /// </summary>
        internal static string AFFILIATECODE_NOT_ALLOW_EMPTY {
            get {
                return ResourceManager.GetString("AFFILIATECODE_NOT_ALLOW_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount must be between {0} and {1}.
        /// </summary>
        internal static string AMOUNT_MUST_BE_IN_BETWEEN {
            get {
                return ResourceManager.GetString("AMOUNT_MUST_BE_IN_BETWEEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bank account code already exist in system.
        /// </summary>
        internal static string BANK_ACCOUNT_CODE_DUPLICATE {
            get {
                return ResourceManager.GetString("BANK_ACCOUNT_CODE_DUPLICATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bank account group already exist in system.
        /// </summary>
        internal static string BANK_ACCOUNT_GROUP_RECORD_DUPLICATE {
            get {
                return ResourceManager.GetString("BANK_ACCOUNT_GROUP_RECORD_DUPLICATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bank account already exist in system.
        /// </summary>
        internal static string BANK_RECORD_DUPLICATE {
            get {
                return ResourceManager.GetString("BANK_RECORD_DUPLICATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Number Existed.
        /// </summary>
        internal static string CONTACT_NUMBER_DUPLICATE {
            get {
                return ResourceManager.GetString("CONTACT_NUMBER_DUPLICATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective date must be later than today.
        /// </summary>
        internal static string CURRENCY_EFFECTIVEDATE_EARLIER_TODAY {
            get {
                return ResourceManager.GetString("CURRENCY_EFFECTIVEDATE_EARLIER_TODAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency cannot be found.
        /// </summary>
        internal static string CURRENCY_NOT_FOUND {
            get {
                return ResourceManager.GetString("CURRENCY_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data access error.
        /// </summary>
        internal static string DATA_ACCESS_ERROR {
            get {
                return ResourceManager.GetString("DATA_ACCESS_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate data.
        /// </summary>
        internal static string DATA_DUPLICATED {
            get {
                return ResourceManager.GetString("DATA_DUPLICATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The login name is unavailable. Please try another login name.
        /// </summary>
        internal static string DATA_DUPLICATED_LOGINNAME {
            get {
                return ResourceManager.GetString("DATA_DUPLICATED_LOGINNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data reference cannot be found.
        /// </summary>
        internal static string DATA_REFERENCE_NOT_FOUND {
            get {
                return ResourceManager.GetString("DATA_REFERENCE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid document.
        /// </summary>
        internal static string DOCUMENT_INVALID_INFO {
            get {
                return ResourceManager.GetString("DOCUMENT_INVALID_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document cannot be found.
        /// </summary>
        internal static string DOCUMENT_NOT_FOUND {
            get {
                return ResourceManager.GetString("DOCUMENT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Exist.
        /// </summary>
        internal static string EMAIL_EXIST {
            get {
                return ResourceManager.GetString("EMAIL_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is invalid.
        /// </summary>
        internal static string EMAIL_INVALID {
            get {
                return ResourceManager.GetString("EMAIL_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Error.
        /// </summary>
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured, please try again or contact Customer Service for assistance..
        /// </summary>
        internal static string GeneralError {
            get {
                return ResourceManager.GetString("GeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured, please try again or contact Customer Service for assistance..
        /// </summary>
        internal static string GeneralErrorR {
            get {
                return ResourceManager.GetString("GeneralErrorR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Parameter.
        /// </summary>
        internal static string GeneralInvalidParameter {
            get {
                return ResourceManager.GetString("GeneralInvalidParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System cannot accept a segment without any greeting message, please input at least one greeting..
        /// </summary>
        internal static string GREETING {
            get {
                return ResourceManager.GetString("GREETING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live TV is only available to customers who have a balance or have placed a bet in the last 24 hours..
        /// </summary>
        internal static string LIVESTREAMING_ERROR {
            get {
                return ResourceManager.GetString("LIVESTREAMING_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance cannot be found.
        /// </summary>
        internal static string MAINTENANCE_NOT_FOUND {
            get {
                return ResourceManager.GetString("MAINTENANCE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance product type cannot be found.
        /// </summary>
        internal static string MAINTENANCE_PRODUCT_TYPE_NOT_FOUND {
            get {
                return ResourceManager.GetString("MAINTENANCE_PRODUCT_TYPE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captcha expired, please refresh captcha.
        /// </summary>
        internal static string MEMBER_CAPTCHA_EXPIRE {
            get {
                return ResourceManager.GetString("MEMBER_CAPTCHA_EXPIRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please contact online customer service.
        /// </summary>
        internal static string MEMBER_CONTACT_CUSTOMERS_SERVICE {
            get {
                return ResourceManager.GetString("MEMBER_CONTACT_CUSTOMERS_SERVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid birthday or underage.
        /// </summary>
        internal static string MEMBER_INVALID_BIRTHDAY {
            get {
                return ResourceManager.GetString("MEMBER_INVALID_BIRTHDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid captcha, please input again.
        /// </summary>
        internal static string MEMBER_INVALID_CAPTCHA {
            get {
                return ResourceManager.GetString("MEMBER_INVALID_CAPTCHA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Emai format provided.
        /// </summary>
        internal static string MEMBER_INVALID_EMAIL {
            get {
                return ResourceManager.GetString("MEMBER_INVALID_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive account, please contact customer service.
        /// </summary>
        internal static string MEMBER_INVALID_LOGIN_INACTIVE_MEMBER {
            get {
                return ResourceManager.GetString("MEMBER_INVALID_LOGIN_INACTIVE_MEMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is locked.
        /// </summary>
        internal static string MEMBER_INVALID_LOGIN_PWD_ISLOCKED {
            get {
                return ResourceManager.GetString("MEMBER_INVALID_LOGIN_PWD_ISLOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is incorrect.
        /// </summary>
        internal static string MEMBER_INVALID_PASSWORD_NOT_MATCH {
            get {
                return ResourceManager.GetString("MEMBER_INVALID_PASSWORD_NOT_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password.
        /// </summary>
        internal static string MEMBER_INVALID_PASSWORD_OR_USERNAME {
            get {
                return ResourceManager.GetString("MEMBER_INVALID_PASSWORD_OR_USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect security information provided.
        /// </summary>
        internal static string MEMBER_INVALID_SECURITY_INFO {
            get {
                return ResourceManager.GetString("MEMBER_INVALID_SECURITY_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is suspended. Please contact Customer Service for assistance..
        /// </summary>
        internal static string MEMBER_INVALID_SUSPENDED_MEMBER {
            get {
                return ResourceManager.GetString("MEMBER_INVALID_SUSPENDED_MEMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been locked. Please contact our customer service..
        /// </summary>
        internal static string MEMBER_LOGIN_FAILURE_ACCOUNT_LOCKED {
            get {
                return ResourceManager.GetString("MEMBER_LOGIN_FAILURE_ACCOUNT_LOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve reached the maximum number of wrong login attempt allowed. Please contact your customer service. .
        /// </summary>
        internal static string MEMBER_LOGIN_FAILURE_CONTACT_CS {
            get {
                return ResourceManager.GetString("MEMBER_LOGIN_FAILURE_CONTACT_CS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login name and email do not match.
        /// </summary>
        internal static string MEMBER_LOGINNAME_OR_EMAIL_NOT_MATCH {
            get {
                return ResourceManager.GetString("MEMBER_LOGINNAME_OR_EMAIL_NOT_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member not found.
        /// </summary>
        internal static string MEMBER_NOT_FOUND {
            get {
                return ResourceManager.GetString("MEMBER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your member account information has been updated by administrator, please login again.
        /// </summary>
        internal static string MEMBER_RESETPASSWORD_KICKOUT {
            get {
                return ResourceManager.GetString("MEMBER_RESETPASSWORD_KICKOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to login. System detected your browser already have other account login..
        /// </summary>
        internal static string MEMBER_SESSION_EXISTS {
            get {
                return ResourceManager.GetString("MEMBER_SESSION_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not sign in! Your account has been logged in elsewhere!.
        /// </summary>
        internal static string MEMBER_SESSION_Kickout {
            get {
                return ResourceManager.GetString("MEMBER_SESSION_Kickout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current network is unstable, kindly check your network connection.
        /// </summary>
        internal static string MEMBER_SESSION_Kickout_ByBO {
            get {
                return ResourceManager.GetString("MEMBER_SESSION_Kickout_ByBO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your session has lost, please login again.
        /// </summary>
        internal static string MEMBER_SESSION_LOST {
            get {
                return ResourceManager.GetString("MEMBER_SESSION_LOST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer failed.
        /// </summary>
        internal static string MEMBER_TRANSFER_FAILED {
            get {
                return ResourceManager.GetString("MEMBER_TRANSFER_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Not Found.
        /// </summary>
        internal static string MEMBER_TRANSFER_NOTFOUND {
            get {
                return ResourceManager.GetString("MEMBER_TRANSFER_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your transfer status is pending.
        /// </summary>
        internal static string MEMBER_TRANSFER_PENDING {
            get {
                return ResourceManager.GetString("MEMBER_TRANSFER_PENDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to remove. There is currently a member tagged by this account tag..
        /// </summary>
        internal static string MEMBER_UNABLE_DELETE_ACCOUNT_TAG {
            get {
                return ResourceManager.GetString("MEMBER_UNABLE_DELETE_ACCOUNT_TAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit failed. Member in self exclusion or admin self exclusion..
        /// </summary>
        internal static string MEMBER_UNABLE_DEPOSIT_SELF_EXCLUSION {
            get {
                return ResourceManager.GetString("MEMBER_UNABLE_DEPOSIT_SELF_EXCLUSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance cannot be negative.
        /// </summary>
        internal static string MEMBERACCOUNT_ACCOUNT_BALANCE_CANNOT_NEGETIVE {
            get {
                return ResourceManager.GetString("MEMBERACCOUNT_ACCOUNT_BALANCE_CANNOT_NEGETIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustment amount greater than balance.
        /// </summary>
        internal static string MEMBERACCOUNT_ADJUSTMENT_AMOUNT_GREATER_THAN_BALANCE {
            get {
                return ResourceManager.GetString("MEMBERACCOUNT_ADJUSTMENT_AMOUNT_GREATER_THAN_BALANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustment status is invalid.
        /// </summary>
        internal static string MEMBERACCOUNT_ADJUSTMENT_INVALID_STATUS {
            get {
                return ResourceManager.GetString("MEMBERACCOUNT_ADJUSTMENT_INVALID_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustment cannot be found.
        /// </summary>
        internal static string MEMBERACCOUNT_ADJUSTMENT_NOT_FOUND {
            get {
                return ResourceManager.GetString("MEMBERACCOUNT_ADJUSTMENT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error processing request (24010001).
        /// </summary>
        internal static string MEMBERACCOUNT_HOLD_TRANSACTION_NOT_EXIST {
            get {
                return ResourceManager.GetString("MEMBERACCOUNT_HOLD_TRANSACTION_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient balance.
        /// </summary>
        internal static string MEMBERACCOUNT_INSUFFICIENT_BALANCE {
            get {
                return ResourceManager.GetString("MEMBERACCOUNT_INSUFFICIENT_BALANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member account is invalid.
        /// </summary>
        internal static string MEMBERACCOUNT_INVALID_STATUS {
            get {
                return ResourceManager.GetString("MEMBERACCOUNT_INVALID_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member not found                .
        /// </summary>
        internal static string MEMBERACCOUNT_NOT_FOUND {
            get {
                return ResourceManager.GetString("MEMBERACCOUNT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error processing request (24010005).
        /// </summary>
        internal static string MEMBERACCOUNT_TRANSACTION_ALREADY_ADD_BALANCE {
            get {
                return ResourceManager.GetString("MEMBERACCOUNT_TRANSACTION_ALREADY_ADD_BALANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error processing request (24010006).
        /// </summary>
        internal static string MEMBERACCOUNT_TRANSACTION_ALREADY_DEDUCT_BALANCE {
            get {
                return ResourceManager.GetString("MEMBERACCOUNT_TRANSACTION_ALREADY_DEDUCT_BALANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error processing request (24010004).
        /// </summary>
        internal static string MEMBERACCOUNT_TRANSACTION_ALREADY_UNHOLD {
            get {
                return ResourceManager.GetString("MEMBERACCOUNT_TRANSACTION_ALREADY_UNHOLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member account transaction is currently on hold.
        /// </summary>
        internal static string MEMBERACCOUNT_TRANSACTION_IS_HOLDING {
            get {
                return ResourceManager.GetString("MEMBERACCOUNT_TRANSACTION_IS_HOLDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Account tag does not exist..
        /// </summary>
        internal static string MEMBERACOUNTTAG_INVALID_ACCOUNTTAG {
            get {
                return ResourceManager.GetString("MEMBERACOUNTTAG_INVALID_ACCOUNTTAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account tag type does not exist..
        /// </summary>
        internal static string MEMBERACOUNTTAG_INVALID_ACCOUNTTAGTYPE {
            get {
                return ResourceManager.GetString("MEMBERACOUNTTAG_INVALID_ACCOUNTTAGTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member does not exist..
        /// </summary>
        internal static string MEMBERACOUNTTAG_INVALID_MEMBER {
            get {
                return ResourceManager.GetString("MEMBERACOUNTTAG_INVALID_MEMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account tag is duplicated..
        /// </summary>
        internal static string MEMBERACOUNTTAG_ONLY_ONE_MEMBER_ACCOUNTTAG_ACCOUNTTAGTYPE {
            get {
                return ResourceManager.GetString("MEMBERACOUNTTAG_ONLY_ONE_MEMBER_ACCOUNTTAG_ACCOUNTTAGTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error processing request (43030006).
        /// </summary>
        internal static string PAYMENT_ACC_STATUS_NOT_ALLOW_CREATE_PAYMENT {
            get {
                return ResourceManager.GetString("PAYMENT_ACC_STATUS_NOT_ALLOW_CREATE_PAYMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount cannot be negative.
        /// </summary>
        internal static string PAYMENT_CHARGEAMOUNT_CANNOT_NEGETIVE {
            get {
                return ResourceManager.GetString("PAYMENT_CHARGEAMOUNT_CANNOT_NEGETIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank charge must be less than gross amount.
        /// </summary>
        internal static string PAYMENT_CHARGEAMOUNT_GREATER_THAN_GROSSAMOUNT {
            get {
                return ResourceManager.GetString("PAYMENT_CHARGEAMOUNT_GREATER_THAN_GROSSAMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error processing request (43030008). Please retry again..
        /// </summary>
        internal static string PAYMENT_DEPOSIT_ERROR {
            get {
                return ResourceManager.GetString("PAYMENT_DEPOSIT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit is failed. Your deposit amount has exceeded your {0} deposit limit..
        /// </summary>
        internal static string PAYMENT_DEPOSIT_LIMIT_EXCEED {
            get {
                return ResourceManager.GetString("PAYMENT_DEPOSIT_LIMIT_EXCEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount cannot be negative or zero.
        /// </summary>
        internal static string PAYMENT_GROSSAMOUNT_CANNOT_NEGETIVE_OR_ZERO {
            get {
                return ResourceManager.GetString("PAYMENT_GROSSAMOUNT_CANNOT_NEGETIVE_OR_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment status is invalid..
        /// </summary>
        internal static string PAYMENT_INVALID_STATUS {
            get {
                return ResourceManager.GetString("PAYMENT_INVALID_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to submit deposit. Please contact customer service for assistance..
        /// </summary>
        internal static string PAYMENT_NO_ACTIVE_PAYMENTTYPE_IS_FOUND {
            get {
                return ResourceManager.GetString("PAYMENT_NO_ACTIVE_PAYMENTTYPE_IS_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member&apos;s current payment status does not allow withdrawal to proceed.
        /// </summary>
        internal static string PAYMENT_PAY_STATUS_NOT_ALLOW_PROCESS_PAYMENT {
            get {
                return ResourceManager.GetString("PAYMENT_PAY_STATUS_NOT_ALLOW_PROCESS_PAYMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allow to submit a withdrawal transaction as we are still processing your previous withdrawal request.
        ///We apologize for any inconveniences..
        /// </summary>
        internal static string PAYMENT_PROCESSINGWITHDRAWAL_REQUEST_EXISTS {
            get {
                return ResourceManager.GetString("PAYMENT_PROCESSINGWITHDRAWAL_REQUEST_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allow to submit a withdrawal transaction as we are still processing your previous withdrawal request.
        ///We apologize for any inconveniences..
        /// </summary>
        internal static string PAYMENT_PROCESSINGWITHDRAWAL_REQUEST_EXISTSR88 {
            get {
                return ResourceManager.GetString("PAYMENT_PROCESSINGWITHDRAWAL_REQUEST_EXISTSR88", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reimbursement amount is greater than charge amount.
        /// </summary>
        internal static string PAYMENT_REIMBURSETAMOUNT_GREATER_THAN_CHARGEAMOUNT {
            get {
                return ResourceManager.GetString("PAYMENT_REIMBURSETAMOUNT_GREATER_THAN_CHARGEAMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount exceeds maximum allowed.
        /// </summary>
        internal static string PAYMENT_SETTING_EXCEED_ACC_STATUS_MAX_AMOUNT {
            get {
                return ResourceManager.GetString("PAYMENT_SETTING_EXCEED_ACC_STATUS_MAX_AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your amount exceed the maximum limit allowed by the system.
        /// </summary>
        internal static string PAYMENT_SETTING_EXCEED_MAX_AMOUNT {
            get {
                return ResourceManager.GetString("PAYMENT_SETTING_EXCEED_MAX_AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your amount is less than the minimum limit allowed by the system.
        /// </summary>
        internal static string PAYMENT_SETTING_LESS_MIN_AMOUNT {
            get {
                return ResourceManager.GetString("PAYMENT_SETTING_LESS_MIN_AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error processing request (43030101).
        /// </summary>
        internal static string PAYMENT_SETTING_NOT_FOUND {
            get {
                return ResourceManager.GetString("PAYMENT_SETTING_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The status for this transaction was recently modified. Please refresh the page and try again..
        /// </summary>
        internal static string PAYMENT_TRANSACTION_STATUS_MODIFIED {
            get {
                return ResourceManager.GetString("PAYMENT_TRANSACTION_STATUS_MODIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to submit deposit. Please contact customer service for assistance..
        /// </summary>
        internal static string PAYMENT_UNABLE_SUBMIT_DEPOSIT {
            get {
                return ResourceManager.GetString("PAYMENT_UNABLE_SUBMIT_DEPOSIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to submit withdrawal. Please contact customer service for assistance..
        /// </summary>
        internal static string PAYMENT_UNABLE_SUBMIT_WITHDRAWAL {
            get {
                return ResourceManager.GetString("PAYMENT_UNABLE_SUBMIT_WITHDRAWAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There Is No Available Payment Option For Your Country And Currency.
        /// </summary>
        internal static string PAYMENT_WHITEBLACKLIST {
            get {
                return ResourceManager.GetString("PAYMENT_WHITEBLACKLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This partner (Playtech A-Gaming) balance is not sufficient. Please contact Customer Service to help you..
        /// </summary>
        internal static string PLAYTECH_AGAMING_KIOSKBALANCE_NOT_SUFFICIENT {
            get {
                return ResourceManager.GetString("PLAYTECH_AGAMING_KIOSKBALANCE_NOT_SUFFICIENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The role already exist in system.
        /// </summary>
        internal static string ROLE_RECORD_DUPLICATE {
            get {
                return ResourceManager.GetString("ROLE_RECORD_DUPLICATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed in adding or editing this greetng segment because system already had other active segment with duplicated display period..
        /// </summary>
        internal static string SEGMENT_DUPLICATE_PERIOD {
            get {
                return ResourceManager.GetString("SEGMENT_DUPLICATE_PERIOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill out field : Segment Name.
        /// </summary>
        internal static string SEGMENT_NAME {
            get {
                return ResourceManager.GetString("SEGMENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segment name already exisits, please rename it..
        /// </summary>
        internal static string SEGMENT_NAME_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("SEGMENT_NAME_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is incorrect..
        /// </summary>
        internal static string USER_EMAIL_NOT_MATCH {
            get {
                return ResourceManager.GetString("USER_EMAIL_NOT_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or email entered is incorrect..
        /// </summary>
        internal static string USER_ID_OR_EMAIL_NOT_MATCH {
            get {
                return ResourceManager.GetString("USER_ID_OR_EMAIL_NOT_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive user. Please contact risk team..
        /// </summary>
        internal static string USER_INACTIVE {
            get {
                return ResourceManager.GetString("USER_INACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user already exist in system.
        /// </summary>
        internal static string USER_RECORD_DUPLICATE {
            get {
                return ResourceManager.GetString("USER_RECORD_DUPLICATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is account(s) under your email with Inactive status. System will only process active account. Please contact risk team for further assistance..
        /// </summary>
        internal static string USER_SOME_ACCOUNTS_INACTIVE {
            get {
                return ResourceManager.GetString("USER_SOME_ACCOUNTS_INACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The whitelist ip already exist in system.
        /// </summary>
        internal static string WHITELIST_RECORD_DUPLICATE {
            get {
                return ResourceManager.GetString("WHITELIST_RECORD_DUPLICATE", resourceCulture);
            }
        }
    }
}
